### PR TITLE
Fixed "quiet" bug - Issue #71

### PR DESCRIPTION
**Pull request by MLpranav**
Issue #71 

Credits to @arttuperala.

### CODE REVIEW

**Comment by aaronkazah** [comment]
Why isn't this approved yet?

**Comment by aaronkazah** [comment]
@jarrekk

**Comment by lunarchy** [comment]
can someone approve this already? it's been months and there's no reason why it wouldn't be approved @jarrekk

**Comment by mahdizojaji** [comment]
Please approve this pull request.
i have a same issue and this pull request fix that.

**Comment by jarrekk** [comment]
Sorry for the late approval, I was busy with some life stuff, would someone want to co-maintain this repo? In case I maybe not reply in time.

**Comment by DinVyapari** [comment]
Hey there! 

I can become a co-maintainer. Do let me know.

**Pull request merged**
